### ISSUE TITLE
Remeber the video played position and resume on loading

### ISSUE THREAD

**Issue by georgi-kovachev** [amzn/web-app-starter-kit-for-fire-tv#22]
Hi,
I am trying to build one page player and I would like to remember the current playing time of the video.
And later when this player page is loading, I would like to start the video  from remembered position.
I implemented the code to work in other TVs like Opera Web TV and Panasonic TV but on Amazon Fire TV I couldn't work with cookie. The minute I visit the page the cookie value is empty.
I can solve this issue? If not cookie what other mechanism should I use?
Thanks

**Comment by craigcbrunner-amazon** [comment]
Hey,
Cookies should definitely work, maybe your cookie is expiring?
Alternatively you can use HTML5 Local storage:
http://www.w3schools.com/html/html5_webstorage.asp
Which should be easy to use for what you want.
Let me know if this helps!
Thanks,
Craig

On Jul 9, 2015, at 11:27 AM, georgi-kovachev <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I am trying to build one page player and I would like to remember the current playing time of the video.
And later when this player page is loading, I would like to start the video from remembered position.
I implemented the code to work in other TVs like Opera Web TV and Panasonic TV but on Amazon Fire TV I couldn't work with cookie. The minute I visit the page the cookie value is empty.
I can solve this issue? If not cookie what other mechanism should I use?
Thanks

**Comment by georgi-kovachev** [comment]
Hi, Craig.
the cookie is not working.
I have two questions.

1. Can you give some sample app which cookie works?
our test url is 
http://fire.vibrant.tv/vibrantvideo/42-agony-aunts-promo?layout=player

2. I think amazon fire tv is working on web view on android device.
If it is true, that web view supports cookie?

Thanks

Looking forward your reply

**Comment by georgi-kovachev** [comment]
I also switched to use localstorage on same url but it is still not working on TV.
Can I use any kind of emulator?
Thanks

**Comment by russellbeattie-amazon** [comment]
Hi Georgi,

Yes, the WebView on the Fire TV supports both cookies and localStorage, so something must be wrong with your code or your setup. Here's some links that you might find useful: 

[Getting the most out of the Web App Tester](https://developer.amazon.com/public/community/post/Tx180EWSRWZ8LHN/Getting-the-most-out-of-the-Web-App-Tester)

[Creating and Publishing a Cordova Hybrid Web App on the Amazon Appstore](https://developer.amazon.com/public/community/post/TxBVXZ2EHPWM96/Creating-and-Publishing-a-Cordova-Hybrid-Web-App-on-the-Amazon-Appstore)

Good luck!

-Russ

**Comment by georgi-kovachev** [comment]
Hi, Russ.
We are testing the url on web app tester.
Is web app tester supporting cookie and localstorage?

And in my experience, when we use cookie function in webview, it doesn't generate any error but cookie is not saving details, for example webview in iOS.

Thanks

**Comment by russellbeattie-amazon** [comment]
Try this:

https://output.jsbin.com/yotaxidomo

https://jsbin.com/yotaxidomo/edit?html

I just loaded it up in the Web App Tester and it works as expected. 

Hope that helps!

-Russ

**Comment by georgi-kovachev** [comment]
it works.
It will give me the clue to investigate my problem.
Thanks
